'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createShop,hash,scan}=require('./server');
const {createConfig}=require('./create-config');
(async function() {
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'magictupper-test-'));
  let server,secondServer;
  const originalReaddir=fs.promises.readdir;
  const originalReaddirSync=fs.readdirSync;
  try {
    const generatedPath=path.join(temp,'container','config.json');
    await assert.rejects(createConfig({name:'Test',username:'test',password:'short'},generatedPath));
    assert.equal(fs.existsSync(generatedPath),false);
    await createConfig({name:'Servidor NAS',username:'test',password:'container-test-password'},generatedPath);
    const generated=JSON.parse(fs.readFileSync(generatedPath,'utf8'));
    assert.equal(generated.library,'/library');
    assert.equal(generated.passwordHash,await hash('container-test-password',generated.passwordSalt));
    assert.ok(!fs.readFileSync(generatedPath,'utf8').includes('container-test-password'));
    fs.mkdirSync(path.join(temp,'juegos'));
    fs.mkdirSync(path.join(temp,'dlc'));
    fs.mkdirSync(path.join(temp,'NINTENDO SWITCH APPS'));
    fs.mkdirSync(path.join(temp,'Updates'));
    fs.mkdirSync(path.join(temp,'NINTENDO SWITCH'));
    fs.writeFileSync(path.join(temp,'juegos','Prueba.nsp'),'0123456789');
    const transferData=require('node:crypto').randomBytes(8*1024*1024);
    fs.writeFileSync(path.join(temp,'juegos','Transferencia.nsp'),transferData);
    fs.writeFileSync(path.join(temp,'dlc','Extra.nsp'),'DLC');
    fs.writeFileSync(path.join(temp,'NINTENDO SWITCH APPS','Homebrew.nro'),'APP');
    fs.writeFileSync(path.join(temp,'Updates','Update.nsp'),'UPDATE');
    fs.writeFileSync(path.join(temp,'NINTENDO SWITCH','Juego.nsp'),'GAME');
    fs.writeFileSync(path.join(temp,'secreto.txt'),'no publicar');
    const hidden=path.join(temp,'NINTENDO SWITCH','magicTupper','.tools');
    fs.mkdirSync(hidden,{recursive:true});
    fs.writeFileSync(path.join(hidden,'internal.bin'),'not a game');
    const failHidden=directory=>{if(directory===hidden)throw Object.assign(new Error('Simulated browser profile I/O error'),{code:'EIO',path:hidden});};
    fs.readdirSync=function(directory,...args){failHidden(directory);return originalReaddirSync.call(this,directory,...args);};
    assert.equal(scan(temp).length,6,'El escáner síncrono no entra en .tools aunque su lectura falle');
    fs.readdirSync=originalReaddirSync;
    const salt='ab'.repeat(16);
    fs.promises.readdir=async function(directory,...args){
      if(directory===temp)throw Object.assign(new Error('Simulated inaccessible library'),{code:'EACCES',syscall:'scandir',path:temp});
      return originalReaddir.call(this,directory,...args);
    };
    server=createShop({name:'Test',library:temp,username:'test',passwordSalt:salt,passwordHash:await hash('password-for-tests',salt)},temp);
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
    const base='http://127.0.0.1:'+server.address().port;
    const get=(url,opts)=>fetch(base+url,opts);
    assert.equal((await get('/api/catalog')).status,401);
    assert.equal((await get('/api/login',{method:'POST',body:'null'})).status,400);
    assert.equal((await get('/api/login',{method:'POST',body:JSON.stringify({username:'test',password:'incorrecta'})})).status,401);
    const login=await get('/api/login',{method:'POST',body:JSON.stringify({username:'test',password:'password-for-tests'})});
    assert.equal(login.status,200);
    const {token}=await login.json(),headers={Authorization:'Bearer '+token};
    const failedCatalog=await get('/api/catalog',{headers});
    assert.equal(failedCatalog.status,500);
    const failureBody=await failedCatalog.json();
    assert.equal(failureBody.code,'CATALOG_SCAN_FAILED');
    assert.ok(!JSON.stringify(failureBody).includes(temp));
    assert.equal((await get('/health')).status,200,'El fallo inicial de escaneo no termina el servidor');
    fs.promises.readdir=async function(directory,...args){failHidden(directory);return originalReaddir.call(this,directory,...args);};
    assert.equal((await get('/api/catalog',{headers})).status,200,'El catálogo se recupera al volver a estar accesible la biblioteca');
    secondServer=createShop({name:'Otra fuente',library:temp,dataDir:'second-data',username:'second',passwordSalt:salt,passwordHash:await hash('second-test-password',salt)},temp);
    await new Promise(resolve=>secondServer.listen(0,'127.0.0.1',resolve));
    const secondBase='http://127.0.0.1:'+secondServer.address().port;
    assert.equal((await fetch(secondBase+'/api/catalog',{headers})).status,401,'Un servidor no acepta la sesión de otro');
    const secondLogin=await fetch(secondBase+'/api/login',{method:'POST',body:JSON.stringify({username:'second',password:'second-test-password'})});
    assert.equal(secondLogin.status,200);
    const secondToken=(await secondLogin.json()).token,secondHeaders={Authorization:'Bearer '+secondToken};
    assert.equal((await get('/api/catalog',{headers:secondHeaders})).status,401);
    assert.equal((await (await fetch(secondBase+'/api/catalog',{headers:secondHeaders})).json()).shop.name,'Otra fuente');
    const catalog=await (await get('/api/catalog',{headers})).json();
    assert.equal(catalog.items.length,6);
    assert.ok(!JSON.stringify(catalog).includes(temp));
    assert.equal(catalog.items.find(x=>x.title==='Prueba').relativePath,'juegos/Prueba.nsp');
    assert.ok(catalog.items.every(x=>!x.relativePath.startsWith('/')&&!x.relativePath.includes('\\')&&!x.relativePath.includes('..')));
    assert.ok(!JSON.stringify(catalog).includes('secreto.txt'));
    assert.equal(catalog.items.find(x=>x.title==='Extra').category,'dlc');
    assert.equal(catalog.items.find(x=>x.title==='Homebrew').category,'apps');
    assert.equal(catalog.items.find(x=>x.title==='Update').category,'updates');
    assert.equal(catalog.items.find(x=>x.title==='Juego').category,'games');
    const game=catalog.items.find(x=>x.title==='Prueba');
    const url='/api/files/'+game.id;
    assert.equal((await get(url)).status,401);
    assert.equal(await (await get(url,{headers})).text(),'0123456789');
    const partial=await get(url,{headers:{...headers,Range:'bytes=3-6'}});
    assert.equal(partial.status,206); assert.equal(await partial.text(),'3456');
    assert.equal(partial.headers.get('content-range'),'bytes 3-6/10');
    const resume=await get(url,{headers:{...headers,Range:'bytes=7-'}});
    assert.equal(await resume.text(),'789');
    assert.equal((await get(url,{headers:{...headers,Range:'bytes=100-'}})).status,416);
    // Simular una conexión interrumpida y reconstruir el archivo por Range.
    const transferUrl='/api/files/'+catalog.items.find(x=>x.title==='Transferencia').id;
    const interrupted=await get(transferUrl,{headers});
    const reader=interrupted.body.getReader();
    const first=await reader.read();
    assert.ok(first.value.length>0&&first.value.length<transferData.length);
    await reader.cancel();
    const continued=await get(transferUrl,{headers:{...headers,Range:'bytes='+first.value.length+'-'}});
    assert.equal(continued.status,206);
    assert.equal(continued.headers.get('content-range'),'bytes '+first.value.length+'-'+(transferData.length-1)+'/'+transferData.length);
    assert.deepEqual(Buffer.concat([Buffer.from(first.value),Buffer.from(await continued.arrayBuffer())]),transferData);
    assert.equal((await get('/api/files/../../secreto.txt',{headers})).status,404);
    const head=await get(url,{method:'HEAD',headers});
    assert.equal(head.headers.get('content-length'),'10');assert.equal(await head.text(),'');
    fs.writeFileSync(path.join(temp,'juegos','Prueba.nsp'),'cambiado');
    assert.equal((await get(url,{headers})).status,409);
    assert.equal((await get('/api/logout',{method:'POST',headers})).status,200);
    assert.equal((await get('/api/catalog',{headers})).status,401);
    assert.equal((await fetch(secondBase+'/api/catalog',{headers:secondHeaders})).status,200,'Cerrar sesión en una fuente no afecta a la otra');
    for(let i=0;i<2;i++) await get('/api/login',{method:'POST',body:'{}'});
    assert.equal((await get('/api/login',{method:'POST',body:'{}'})).status,429);
    console.log('PASS: sesiones independientes entre dos servidores, autenticación, revocación, límite de intentos, categorías, rutas, descargas, HEAD, rangos y cambios de archivo.');
  } finally {
    fs.promises.readdir=originalReaddir;
    fs.readdirSync=originalReaddirSync;
    if(server) await new Promise(resolve=>server.close(resolve));
    if(secondServer) await new Promise(resolve=>secondServer.close(resolve));
    const cleanupPath=path.resolve(temp),temporaryRoot=path.resolve(os.tmpdir());
    assert.equal(path.dirname(cleanupPath),temporaryRoot);
    assert.ok(path.basename(cleanupPath).startsWith('magictupper-test-'));
    fs.rmSync(cleanupPath,{recursive:true,force:true});
  }
})().catch(err=>{console.error(err);process.exitCode=1;});
