'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createShop,hash}=require('./server');
const {titleMetadata,packageMetadata,browseDirectory}=require('./library');
(async()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'magictupper-library-'));let server;
  try{
    const games=path.join(root,'juegos'),library=path.join(games,'roms','NINTENDO SWITCH');
    for(const dir of ['ROMS','DLC','UPDATES','APPS','retro'])fs.mkdirSync(path.join(library,dir),{recursive:true});
    fs.mkdirSync(path.join(games,'retro','empty'),{recursive:true});
    fs.writeFileSync(path.join(games,'retro','demo.sfc'),'retro content');
    fs.writeFileSync(path.join(library,'ROMS','Game [0100123456780000].xci'),'base');
    fs.writeFileSync(path.join(library,'UPDATES','Game [0100123456780800][v65536].nsp'),'update');
    fs.writeFileSync(path.join(library,'DLC','Extra.nsp'),'dlc');
    fs.writeFileSync(path.join(library,'APPS','Tool.nro'),'app');
    fs.writeFileSync(path.join(library,'retro','Other.sfc'),'excluded');
    fs.writeFileSync(path.join(library,'ROMS','Other.sfc'),'excluded');
    fs.writeFileSync(path.join(library,'APPS','sources.json'),'private');
    fs.writeFileSync(path.join(games,'.hidden'),'hidden');
    assert.deepEqual(titleMetadata('No ID.nsp'),{});
    assert.equal(titleMetadata('Cuphead [0100a5c00d163001].nsp','dlc').applicationId,'0100a5c00d162000');
    assert.equal(titleMetadata('Extra [0100123456781002].nsp','dlc').applicationId,'0100123456780000');
    assert.deepEqual(titleMetadata('[0100123456780000][0100123456780800].nsp'),{});
    assert.equal(titleMetadata('Game [0100123456780800][v65536].nsp').applicationId,'0100123456780000');
    assert.equal(titleMetadata('Game [0100123456780800][v65536].nsp').version,65536);
    assert.equal(titleMetadata('[0100123456780800][v99999999999].nsp').version,null);
    const ticketName=Buffer.from('01001234567808000000000000000000.tik\0');
    const ticketIndex=Buffer.alloc(16+24+ticketName.length+1);ticketIndex.write('PFS0');ticketIndex.writeUInt32LE(1,4);ticketIndex.writeUInt32LE(ticketName.length,8);ticketIndex.writeBigUInt64LE(1n,24);ticketName.copy(ticketIndex,40);
    const ticketFile=path.join(root,'Update v1.3.7.nsp');fs.writeFileSync(ticketFile,ticketIndex);
    assert.equal((await packageMetadata(ticketFile)).applicationId,'0100123456780000');assert.equal((await packageMetadata(ticketFile)).version,null);
    const conflicting=path.join(root,'[0100123456790800].nsp');fs.writeFileSync(conflicting,ticketIndex);assert.deepEqual(await packageMetadata(conflicting),{});
    ticketIndex.writeUInt32LE(0xffffffff,4);fs.writeFileSync(ticketFile,ticketIndex);assert.deepEqual(await packageMetadata(ticketFile),{});
    for(const invalid of ['..','../outside','a/../b','C:/secret','a\\b','.hidden','/absolute','a//b'])await assert.rejects(browseDirectory(games,invalid));
    const salt='ab'.repeat(16);server=createShop({name:'Switch',library,browserRoot:games,catalogMode:'switch',dataDir:path.join(root,'data'),username:'admin',passwordSalt:salt,passwordHash:await hash('password-for-tests',salt)},root);
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
    assert.equal((await fetch(base+'/api/browse')).status,401);
    const login=await (await fetch(base+'/api/login',{method:'POST',body:JSON.stringify({username:'admin',password:'password-for-tests'})})).json();const headers={Authorization:'Bearer '+login.token};
    const catalog=await (await fetch(base+'/api/catalog',{headers})).json();assert.equal(catalog.items.length,4);assert.deepEqual(catalog.items.map(i=>i.category).sort(),['apps','dlc','games','updates']);assert.equal(catalog.items.find(i=>i.category==='updates').version,65536);
    assert.equal((await fetch(base+'/api/admin/users',{headers,method:'POST',body:JSON.stringify({username:'reader',password:'reader-password',role:'standard'})})).status,201);
    const reader=await (await fetch(base+'/api/login',{method:'POST',body:JSON.stringify({username:'reader',password:'reader-password'})})).json();const readHeaders={Authorization:'Bearer '+reader.token};
    const appId=catalog.items.find(i=>i.category==='apps').id;
    assert.equal((await fetch(base+'/api/apps/'+appId)).status,401);
    const app=await (await fetch(base+'/api/apps/'+appId,{headers:readHeaders})).json();assert.equal(app.files.length,1);assert.equal(app.executable,'Tool.nro');assert.equal(await (await fetch(base+'/api/files/'+app.files[0].id,{headers:readHeaders})).text(),'app');
    const listing=await (await fetch(base+'/api/browse?path=retro',{headers:readHeaders})).json();assert.equal(listing.entries.length,2);assert(listing.entries[0].directory);assert(!JSON.stringify(listing).includes(root));
    const file=listing.entries.find(i=>!i.directory);
    assert.equal(await (await fetch(base+'/api/files/'+file.id,{headers:{...readHeaders,Range:'bytes=0-4'}})).text(),'retro');
    assert.equal((await fetch(base+'/api/files/'+file.id,{method:'HEAD',headers:readHeaders})).headers.get('content-length'),'13');
    assert.equal((await fetch(base+'/api/browse?path=..',{headers:readHeaders})).status,400);
    assert.equal((await fetch(base+'/api/browse?path=retro',{headers:readHeaders,method:'DELETE'})).status,403);
    assert.equal((await fetch(base+'/api/browse?path=missing',{headers:readHeaders})).status,404);
    assert.equal((await (await fetch(base+'/api/browse?path=retro/empty',{headers:readHeaders})).json()).entries.length,0);
    fs.writeFileSync(path.join(games,'retro','demo.sfc'),'changed');assert.equal((await fetch(base+'/api/files/'+file.id,{headers:readHeaders})).status,409);
    console.log('PASS: Switch-only catalog, title metadata, independent browser, standard access, ranges and invalid paths');
  }finally{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
