package com.magictupper.remote;
import android.app.*; import android.app.UiModeManager; import android.content.res.Configuration; import android.os.*; import android.graphics.*; import android.graphics.drawable.*; import android.view.*; import android.view.inputmethod.InputMethodManager; import android.content.*; import android.util.Log; import android.widget.*; import android.text.InputType;
public final class MainActivity extends Activity implements RemotePlayClient.Listener {
 private static final String TAG="magicTupper"; private SurfaceView video; private ImageView home; private TextView status; private EditText ip; private Button connectButton,fullscreenButton,rcmButton,exitButton; private RemotePlayClient client; private final PadState pad=new PadState(); private volatile boolean surfaceReady; private boolean fullscreen=false; private LinearLayout controlBar;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(5894);build();}
 private GradientDrawable panel(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)radius));g.setStroke(dp(1),0x3347d7ff);return g;}
 private Button actionButton(String text){Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setMinHeight(0);b.setMinWidth(0);b.setPadding(dp(14),0,dp(14),0);b.setBackground(panel(0xff18222d,12));return b;}
 private void build(){
  FrameLayout root=new FrameLayout(this);root.setBackgroundColor(0xff05080c);
  FrameLayout display=new FrameLayout(this);root.addView(display,new FrameLayout.LayoutParams(-1,-1));
  video=new SurfaceView(this);display.addView(video,new FrameLayout.LayoutParams(-1,-1));
  video.getHolder().addCallback(new SurfaceHolder.Callback(){public void surfaceCreated(SurfaceHolder h){surfaceReady=h.getSurface()!=null&&h.getSurface().isValid();Log.i(TAG,"SURFACE created valid="+surfaceReady);if(connectButton!=null)connectButton.setEnabled(surfaceReady);}public void surfaceChanged(SurfaceHolder h,int f,int w,int he){surfaceReady=h.getSurface()!=null&&h.getSurface().isValid();Log.i(TAG,"SURFACE changed "+w+"x"+he+" valid="+surfaceReady);}public void surfaceDestroyed(SurfaceHolder h){surfaceReady=false;Log.i(TAG,"SURFACE destroyed");if(connectButton!=null)connectButton.setEnabled(false);disconnect("Surface destruida");}});
  home=new ImageView(this);home.setScaleType(ImageView.ScaleType.FIT_CENTER);home.setBackgroundColor(Color.BLACK);home.setVisibility(View.GONE);display.addView(home,new FrameLayout.LayoutParams(-1,-1));

  controlBar=new LinearLayout(this);LinearLayout bar=controlBar;bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(12),dp(8),dp(12),dp(8));bar.setBackground(panel(0xee0d141b,16));
  ImageView logo=new ImageView(this);logo.setImageResource(com.magictupper.remote.R.drawable.magictupper_logo);logo.setScaleType(ImageView.ScaleType.CENTER_CROP);bar.addView(logo,new LinearLayout.LayoutParams(dp(44),dp(44)));
  LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setPadding(dp(10),0,dp(16),0);TextView title=new TextView(this);title.setText("magicTupper");title.setTextColor(Color.WHITE);title.setTextSize(17);title.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);TextView sub=new TextView(this);sub.setText("REMOTE PLAY");sub.setTextColor(0xff6fdcff);sub.setTextSize(10);sub.setLetterSpacing(.14f);brand.addView(title);brand.addView(sub);bar.addView(brand);
  ip=new EditText(this);ip.setSingleLine();ip.setHint("IP de la Switch");ip.setText(getPreferences(0).getString("ip","192.168.2."));ip.setTextColor(Color.WHITE);ip.setHintTextColor(0xff75818d);ip.setTextSize(14);ip.setInputType(InputType.TYPE_CLASS_PHONE);ip.setPadding(dp(12),0,dp(12),0);ip.setBackground(panel(0xff111a23,11));bar.addView(ip,new LinearLayout.LayoutParams(dp(170),dp(44)));
  connectButton=actionButton("Conectar");connectButton.setEnabled(false);connectButton.setOnClickListener(v->connect());LinearLayout.LayoutParams ab=new LinearLayout.LayoutParams(-2,dp(44));ab.setMargins(dp(8),0,0,0);bar.addView(connectButton,ab);
  fullscreenButton=actionButton("Pantalla completa");fullscreenButton.setOnClickListener(v->setFullscreen(true));LinearLayout.LayoutParams fb=new LinearLayout.LayoutParams(-2,dp(44));fb.setMargins(dp(8),0,0,0);bar.addView(fullscreenButton,fb);
  UiModeManager uiMode=(UiModeManager)getSystemService(UI_MODE_SERVICE);boolean isTv=uiMode!=null&&uiMode.getCurrentModeType()==Configuration.UI_MODE_TYPE_TELEVISION;if(!isTv){rcmButton=actionButton("RCM Injector");rcmButton.setOnClickListener(v->startActivity(new Intent(this,RcmActivity.class)));LinearLayout.LayoutParams rb=new LinearLayout.LayoutParams(-2,dp(44));rb.setMargins(dp(8),0,0,0);bar.addView(rcmButton,rb);}
  exitButton=actionButton("Salir");exitButton.setOnClickListener(v->exitApp());LinearLayout.LayoutParams eb=new LinearLayout.LayoutParams(-2,dp(44));eb.setMargins(dp(8),0,0,0);bar.addView(exitButton,eb);
  status=new TextView(this);status.setTextColor(0xffb9c7d4);status.setTextSize(12);status.setText("Preparando vídeo…");status.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);status.setPadding(dp(14),0,0,0);bar.addView(status,new LinearLayout.LayoutParams(0,dp(44),1));
  FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,dp(68),Gravity.TOP);bp.setMargins(dp(14),dp(12),dp(14),0);root.addView(bar,bp);setContentView(root);

  // Touch belongs only to the actual 16:9 display, never to the toolbar/buttons.
  display.setOnTouchListener((v,e)->{
   if(client==null)return false;int am=e.getActionMasked();if(am!=MotionEvent.ACTION_DOWN&&am!=MotionEvent.ACTION_POINTER_DOWN&&am!=MotionEvent.ACTION_MOVE&&am!=MotionEvent.ACTION_POINTER_UP&&am!=MotionEvent.ACTION_UP&&am!=MotionEvent.ACTION_CANCEL)return false;
   int pc=(am==MotionEvent.ACTION_CANCEL||am==MotionEvent.ACTION_UP)?0:e.getPointerCount();int skip=(am==MotionEvent.ACTION_POINTER_UP)?e.getActionIndex():-1;int n=Math.min(10,pc-(skip>=0?1:0));if(n<0)n=0;int[]ids=new int[n];float[]xs=new float[n],ys=new float[n];float vw=v.getWidth(),vh=v.getHeight(),target=16f/9f,cw,ch,ox,oy;if(vw/Math.max(1f,vh)>target){ch=vh;cw=ch*target;ox=(vw-cw)*.5f;oy=0;}else{cw=vw;ch=cw/target;ox=0;oy=(vh-ch)*.5f;}int o=0;for(int i=0;i<pc&&o<n;i++){if(i==skip)continue;float nx=(e.getX(i)-ox)/Math.max(1f,cw),ny=(e.getY(i)-oy)/Math.max(1f,ch);if(nx<0||nx>1||ny<0||ny>1)continue;ids[o]=e.getPointerId(i);xs[o]=nx;ys[o]=ny;o++;}if(o<n){ids=java.util.Arrays.copyOf(ids,o);xs=java.util.Arrays.copyOf(xs,o);ys=java.util.Arrays.copyOf(ys,o);n=o;}client.sendTouch(n==0?0:1,ids,xs,ys,n);return true;
  });
 }
 private void connect(){String h=ip.getText().toString().trim();try{if(h.isEmpty())throw new IllegalArgumentException("IP vacía");if(!surfaceReady||video.getHolder().getSurface()==null||!video.getHolder().getSurface().isValid())throw new IllegalStateException("Surface de vídeo aún no preparada");disconnect(null);getPreferences(0).edit().putString("ip",h).apply();Log.i(TAG,"CONN START ip="+h);client=new RemotePlayClient(this,pad,video.getHolder().getSurface());client.start(h);connectButton.setText("Reconectar");((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(ip.getWindowToken(),0);}catch(Throwable e){Log.e(TAG,"CONN FAILED "+e.getClass().getName()+": "+String.valueOf(e.getMessage()),e);status("Error: "+e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage()));}}
 private void exitApp(){Log.i(TAG,"EXIT requested");disconnect("Salir");finishAndRemoveTask();}
 private void disconnect(String why){RemotePlayClient c=client;client=null;if(c!=null){Log.i(TAG,"CONN close"+(why==null?"":" reason="+why));try{c.close();}catch(Throwable e){Log.e(TAG,"close failed",e);}}}
 @Override public boolean dispatchKeyEvent(KeyEvent e){int bit=map(e.getKeyCode());if(bit!=0){pad.button(bit,e.getAction()==KeyEvent.ACTION_DOWN);return true;}return super.dispatchKeyEvent(e);} @Override public boolean dispatchGenericMotionEvent(MotionEvent e){if((e.getSource()&InputDevice.SOURCE_JOYSTICK)!=0&&e.getAction()==MotionEvent.ACTION_MOVE){pad.lx=PadState.axis(e.getAxisValue(MotionEvent.AXIS_X));pad.ly=PadState.axis(-e.getAxisValue(MotionEvent.AXIS_Y));pad.rx=PadState.axis(e.getAxisValue(MotionEvent.AXIS_Z));pad.ry=PadState.axis(-e.getAxisValue(MotionEvent.AXIS_RZ));float l=e.getAxisValue(MotionEvent.AXIS_LTRIGGER),r=e.getAxisValue(MotionEvent.AXIS_RTRIGGER);pad.lt=(int)(Math.max(0,l)*65535);pad.rt=(int)(Math.max(0,r)*65535);pad.button(PadState.ZL,l>.35);pad.button(PadState.ZR,r>.35);return true;}return super.dispatchGenericMotionEvent(e);}
 private int map(int k){switch(k){
  case KeyEvent.KEYCODE_BUTTON_A:return PadState.B; case KeyEvent.KEYCODE_BUTTON_B:return PadState.A; case KeyEvent.KEYCODE_BUTTON_X:return PadState.Y; case KeyEvent.KEYCODE_BUTTON_Y:return PadState.X;
  case KeyEvent.KEYCODE_BUTTON_L1:return PadState.L; case KeyEvent.KEYCODE_BUTTON_R1:return PadState.R; case KeyEvent.KEYCODE_BUTTON_L2:return PadState.ZL; case KeyEvent.KEYCODE_BUTTON_R2:return PadState.ZR;
  case KeyEvent.KEYCODE_BUTTON_THUMBL:return PadState.L3; case KeyEvent.KEYCODE_BUTTON_THUMBR:return PadState.R3;
  case KeyEvent.KEYCODE_BUTTON_START: case KeyEvent.KEYCODE_MENU:return PadState.PLUS;
  case KeyEvent.KEYCODE_BUTTON_SELECT: case KeyEvent.KEYCODE_BACK:return PadState.MINUS;
  case KeyEvent.KEYCODE_BUTTON_MODE:return PadState.HOME;
  case KeyEvent.KEYCODE_DPAD_UP:return PadState.UP; case KeyEvent.KEYCODE_DPAD_DOWN:return PadState.DOWN; case KeyEvent.KEYCODE_DPAD_LEFT:return PadState.LEFT; case KeyEvent.KEYCODE_DPAD_RIGHT:return PadState.RIGHT;
  default:return 0;}}
 private void setFullscreen(boolean on){fullscreen=on;if(controlBar!=null)controlBar.setVisibility(on?View.GONE:View.VISIBLE);int flags=View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE;getWindow().getDecorView().setSystemUiVisibility(on?flags:5894);Log.i(TAG,"FULLSCREEN "+on);}
 @Override public void onBackPressed(){if(fullscreen){setFullscreen(false);return;}super.onBackPressed();}
 public void status(String s){Log.i(TAG,"STATUS "+s);runOnUiThread(()->status.setText(s));}public void homeFrame(Bitmap b){runOnUiThread(()->{home.setImageBitmap(b);home.setVisibility(View.VISIBLE);});}public void h264Active(){runOnUiThread(()->home.setVisibility(View.GONE));}private int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}@Override protected void onDestroy(){disconnect("Activity destroy");super.onDestroy();}
}
