package com.magictupper.remote;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.hardware.usb.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.security.*;import java.util.concurrent.*;
public final class RcmActivity extends Activity{
 static final String USB_PERMISSION="com.magictupper.remote.USB_PERMISSION"; static final String HEKATE_URL="https://github.com/CTCaer/hekate/releases/download/v6.5.3/hekate_ctcaer_6.5.3.bin"; static final String FUSEE_URL="https://github.com/Atmosphere-NX/Atmosphere/releases/download/1.11.2/fusee.bin";
 final ExecutorService io=Executors.newSingleThreadExecutor(); TextView device,payload,log;Button inject;String selected="hekate";byte[] custom;String customName;UsbManager usb;
 final Handler usbHandler=new Handler(Looper.getMainLooper()); boolean permissionPending=false; String lastApxName="";
 BroadcastReceiver permission=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(USB_PERMISSION.equals(i.getAction())){permissionPending=false;boolean granted=i.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED,false);append(granted?"Permiso USB concedido.":"Permiso USB no concedido.");refresh();}}};
 final Runnable usbPoll=new Runnable(){public void run(){refresh();usbHandler.postDelayed(this,500);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);usb=(UsbManager)getSystemService(USB_SERVICE);IntentFilter f=new IntentFilter(USB_PERMISSION);if(Build.VERSION.SDK_INT>=33)registerReceiver(permission,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(permission,f);build();refresh();}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),0x3347d7ff);return g;} Button btn(String t){Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(0xff18222d,12));return b;}
 void build(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(0xff05080c);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(28),dp(22),dp(28),dp(28));sv.addView(root);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ Atrás");back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(92),dp(48)));ImageView icon=new ImageView(this);icon.setImageResource(R.drawable.magictupper_logo);head.addView(icon,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.setPadding(dp(14),0,0,0);TextView t=txt("Payload Injector",26,Color.WHITE);TextView s=txt("RCM · Nintendo Switch APX 0955:7321",12,0xff70dcff);tt.addView(t);tt.addView(s);head.addView(tt);root.addView(head);
  device=txt("Buscando Switch en RCM…",15,0xffc7d3df);device.setPadding(dp(16),dp(14),dp(16),dp(14));device.setBackground(bg(0xff0e161e,12));LinearLayout.LayoutParams card=new LinearLayout.LayoutParams(-1,-2);card.setMargins(0,dp(20),0,0);root.addView(device,card);
  root.addView(txt("Payload",13,0xff7f91a2),card);LinearLayout choices=new LinearLayout(this);Button h=btn("Hekate 6.5.3 · recomendado");Button f=btn("fusee 1.11.2 · Atmosphère");Button c=btn("Archivo .bin…");h.setOnClickListener(v->{selected="hekate";custom=null;updatePayload();});f.setOnClickListener(v->{selected="fusee";custom=null;updatePayload();});c.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/octet-stream").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,44);});choices.addView(h,new LinearLayout.LayoutParams(0,dp(52),1));choices.addView(f,new LinearLayout.LayoutParams(0,dp(52),1));choices.addView(c,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(choices);
  payload=txt("",14,0xffb9c7d4);payload.setPadding(0,dp(10),0,0);root.addView(payload);updatePayload();inject=btn("Inyectar payload");inject.setTextSize(17);inject.setOnClickListener(v->beginInject());LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(58));ip.setMargins(0,dp(18),0,0);root.addView(inject,ip);
  TextView warn=txt("La inyección solo funciona por RCM/Fusée Gelée en consolas vulnerables. No se ejecuta automáticamente al conectar USB.",12,0xffffc46b);warn.setPadding(dp(14),dp(12),dp(14),dp(12));warn.setBackground(bg(0xff201a0e,10));root.addView(warn,card);log=txt("Listo.",12,0xff91a3b4);log.setPadding(dp(14),dp(14),dp(14),dp(14));log.setBackground(bg(0xff0b1117,10));root.addView(log,card);setContentView(sv);
 }
 TextView txt(String x,int z,int c){TextView t=new TextView(this);t.setText(x);t.setTextSize(z);t.setTextColor(c);return t;} void updatePayload(){payload.setText(custom!=null?("Personalizado · "+customName+" · "+custom.length+" bytes"):(selected.equals("hekate")?"Hekate 6.5.3 · se descarga/caché desde el release oficial":"fusee 1.11.2 · se descarga/caché desde el release oficial de Atmosphère"));}
 void refresh(){
  java.util.HashMap<String,UsbDevice> all=usb.getDeviceList(); UsbDevice d=RcmInjector.find(usb);
  if(d==null){if(!lastApxName.isEmpty()){append("APX desconectado.");lastApxName="";}permissionPending=false;device.setText("USB Host activo · dispositivos visibles: "+all.size()+"\nAPX 0955:7321: no detectado");inject.setEnabled(false);return;}
  String name=d.getDeviceName();if(!name.equals(lastApxName)){lastApxName=name;permissionPending=false;append("APX detectado · "+name+" · interfaces="+d.getInterfaceCount());}
  boolean ok=usb.hasPermission(d);device.setText("USB Host activo · dispositivos visibles: "+all.size()+"\nAPX 0955:7321: detectado · permiso: "+(ok?"sí":"no"));inject.setEnabled(ok);
  if(ok){permissionPending=false;return;}
  if(!permissionPending){permissionPending=true;int flags=PendingIntent.FLAG_UPDATE_CURRENT;if(Build.VERSION.SDK_INT>=31)flags|=PendingIntent.FLAG_MUTABLE;PendingIntent pi=PendingIntent.getBroadcast(this,1001,new Intent(USB_PERMISSION).setPackage(getPackageName()),flags);append("Solicitando permiso Android para APX…");try{usb.requestPermission(d,pi);}catch(Exception e){permissionPending=false;append("Error solicitando permiso: "+e.getMessage());}}
 }
 void beginInject(){UsbDevice d=RcmInjector.find(usb);if(d==null){refresh();return;}inject.setEnabled(false);append("Preparando "+(custom!=null?customName:selected)+"…");io.execute(()->{try{byte[] data=custom!=null?custom:getPreset(selected);runOnUiThread(()->append("SHA-256 "+sha(data)));RcmInjector.inject(this,d,data,x->runOnUiThread(()->append(x)));runOnUiThread(()->{append("✓ Finalizado");inject.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{append("✕ "+e.getMessage());inject.setEnabled(true);});}});}
 byte[] getPreset(String n)throws Exception{File f=new File(getFilesDir(),n.equals("hekate")?"hekate-6.5.3.bin":"fusee-1.11.2.bin");if(f.isFile()&&f.length()>512)return read(new FileInputStream(f));String u=n.equals("hekate")?HEKATE_URL:FUSEE_URL;runOnUiThread(()->append("Descargando preset oficial…"));HttpURLConnection h=(HttpURLConnection)new URL(u).openConnection();h.setConnectTimeout(10000);h.setReadTimeout(20000);h.setInstanceFollowRedirects(true);if(h.getResponseCode()/100!=2)throw new IOException("Descarga HTTP "+h.getResponseCode());byte[] b=read(h.getInputStream());try(FileOutputStream o=new FileOutputStream(f)){o.write(b);}return b;}
 byte[] read(InputStream i)throws IOException{return RcmInjector.readAll(i);}String sha(byte[]b){try{byte[]d=MessageDigest.getInstance("SHA-256").digest(b);StringBuilder s=new StringBuilder();for(byte x:d)s.append(String.format("%02x",x));return s.toString();}catch(Exception e){return "n/a";}}void append(String x){log.setText(log.getText()+"\n"+x);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==44&&c==RESULT_OK&&data!=null){Uri u=data.getData();try{custom=read(getContentResolver().openInputStream(u));customName=u.getLastPathSegment();selected="custom";updatePayload();}catch(Exception e){append("No se pudo leer: "+e.getMessage());}}}
 @Override protected void onResume(){super.onResume();usbHandler.removeCallbacks(usbPoll);refresh();usbHandler.postDelayed(usbPoll,500);}@Override protected void onPause(){usbHandler.removeCallbacks(usbPoll);super.onPause();}@Override protected void onDestroy(){usbHandler.removeCallbacks(usbPoll);try{unregisterReceiver(permission);}catch(Exception ignored){}io.shutdownNow();super.onDestroy();}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
}
