package com.magictupper.remote;
import android.graphics.*; import android.media.*; import android.util.Log; import android.view.Surface; import java.io.*; import java.net.*; import java.nio.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.*;
final class RemotePlayClient implements AutoCloseable {
 interface Listener{void status(String s);void homeFrame(Bitmap b);void h264Active();} private static final String TAG="magicTupper";
 private final Listener listener;private final PadState pad;private final Surface surface;private volatile boolean running;private final AtomicBoolean closed=new AtomicBoolean();private DatagramSocket video,audio,input;private InetAddress host;private H264SurfaceDecoder decoder;private AudioTrack audioTrack;private ScheduledExecutorService inputExec;private final AtomicInteger seq=new AtomicInteger();private final AtomicReference<byte[]> latestTouchPacket=new AtomicReference<>();private final AtomicInteger touchReleaseRepeats=new AtomicInteger();private long touchTxPkts;private long lastH264Ms;private long videoPkts,mtjPkts,mtjLikePkts,pt96Pkts,otherVideoPkts,audioRawPkts,audioPkts,audioBytes,h264Frames,homeFrames,padPkts,lastStatsMs;private int lastVideoSeq=-1;private long rtpLoss;
 private int jpegFid=-1,jpegTotal,jpegGot;private byte[]jpegBuf;private boolean[]jpegChunks;private int latestFid=-1;private final AtomicReference<byte[]> latestJpeg=new AtomicReference<>();private Thread jpegWorker;
 private ByteArrayOutputStream au=new ByteArrayOutputStream(256*1024),frag;private int currentTs=-1;private boolean waitingIdr=true,auIdr;
 RemotePlayClient(Listener l,PadState p,Surface s){listener=l;pad=p;surface=s;}
 void start(String ip)throws Exception{if(surface==null||!surface.isValid())throw new IllegalStateException("Surface inválida");host=InetAddress.getByName(ip);Log.i(TAG,"START host="+host.getHostAddress());video=new DatagramSocket();video.setReceiveBufferSize(8*1024*1024);video.setSoTimeout(250);audio=new DatagramSocket();audio.setReceiveBufferSize(2*1024*1024);audio.setSoTimeout(500);input=new DatagramSocket();Log.i(TAG,"SOCKET videoLocal="+video.getLocalPort()+" audioLocal="+audio.getLocalPort()+" inputLocal="+input.getLocalPort());decoder=new H264SurfaceDecoder(surface);Log.i(TAG,"H264 decoder started");setupAudio();running=true;lastStatsMs=System.currentTimeMillis();inputExec=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"MT-input");t.setDaemon(true);return t;});sendAsync(audio,"MTV2|AUDIO|HELLO",8769);sendAsync(video,"MTV2|START|AUDIO=1|APORT="+audio.getLocalPort(),8768);Log.i(TAG,"CTRL START queued ->8768 APORT="+audio.getLocalPort());Thread vt=new Thread(this::videoLoop,"MT-video");vt.setDaemon(true);vt.start();Thread at=new Thread(this::audioLoop,"MT-audio");at.setDaemon(true);at.start();jpegWorker=new Thread(this::jpegDecodeLoop,"MT-jpeg");jpegWorker.setDaemon(true);jpegWorker.start();inputExec.scheduleAtFixedRate(this::sendPad,0,4,TimeUnit.MILLISECONDS);inputExec.scheduleAtFixedRate(this::sendTouchLatest,0,16,TimeUnit.MILLISECONDS);listener.status("Conectando a "+ip+"…");}
 private void setupAudio(){int min=AudioTrack.getMinBufferSize(48000,AudioFormat.CHANNEL_OUT_STEREO,AudioFormat.ENCODING_PCM_16BIT);audioTrack=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build()).setAudioFormat(new AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(48000).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO).build()).setBufferSizeInBytes(Math.max(min,32768)).setTransferMode(AudioTrack.MODE_STREAM).setPerformanceMode(AudioTrack.PERFORMANCE_MODE_LOW_LATENCY).build();audioTrack.play();Log.i(TAG,"AUDIO started min="+min+" state="+audioTrack.getState());}
 private void videoLoop(){byte[]buf=new byte[65535];long ping=0;while(running){try{long n=System.currentTimeMillis();if(n-ping>1000){send(video,"MTV2|PING",8768);ping=n;}DatagramPacket dp=new DatagramPacket(buf,buf.length);try{video.receive(dp);}catch(SocketTimeoutException timeout){stats();continue;}if(!dp.getAddress().equals(host))continue;videoPkts++;byte[]p=Arrays.copyOf(dp.getData(),dp.getLength());if(p.length>=4&&p[0]=='M'&&p[1]=='T'&&p[2]=='J'&&p[3]=='1'){mtjPkts++;jpeg(p);stats();continue;}if(p.length>=3&&p[0]=='M'&&p[1]=='T'&&p[2]=='J'){mtjLikePkts++;if(mtjLikePkts<=5)Log.w(TAG,"MTJ unknown header len="+p.length+" head="+hexHead(p,16));stats();continue;}if(p.length>=4&&p[0]=='M'&&p[1]=='T'&&p[2]=='V'&&p[3]=='2'){String s=new String(p,StandardCharsets.UTF_8);Log.i(TAG,"CTRL RX "+s);if(s.startsWith("MTV2|OK|"))listener.status("Conectado · Remote Play activo");stats();continue;}if(p.length>=2&&(p[0]&0xC0)==0x80&&(p[1]&0x7f)==96)pt96Pkts++;else{otherVideoPkts++;if(otherVideoPkts<=8)Log.w(TAG,"VIDEO unknown len="+p.length+" head="+hexHead(p,24));}rtpVideo(p);stats();}catch(Throwable e){if(running){Log.e(TAG,"VIDEO loop",e);listener.status("Vídeo: "+e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage()));}}}Log.i(TAG,"VIDEO loop exit");}
 private void jpeg(byte[]p){if(System.currentTimeMillis()-lastH264Ms<120)return;int fid=be32(p,4),off=be32(p,8),total=be32(p,12),count=p.length-16;if(total<=0||total>4*1024*1024||off<0||off+count>total)return;if(latestFid!=-1&&Integer.compareUnsigned(fid,latestFid)<0)return;if(latestFid==-1||Integer.compareUnsigned(fid,latestFid)>0)latestFid=fid;int chunks=(total+1183)/1184;if(fid!=jpegFid||jpegBuf==null||jpegTotal!=total){jpegFid=fid;jpegTotal=total;jpegBuf=new byte[total];jpegChunks=new boolean[chunks];jpegGot=0;}System.arraycopy(p,16,jpegBuf,off,count);int ci=off/1184;if(ci>=0&&ci<jpegChunks.length&&!jpegChunks[ci]){jpegChunks[ci]=true;jpegGot++;}if(jpegGot==jpegChunks.length){byte[]done=jpegBuf;jpegBuf=null;jpegChunks=null;latestJpeg.set(done);}}
 private void jpegDecodeLoop(){while(running){try{byte[]done=latestJpeg.getAndSet(null);if(done==null){Thread.sleep(4);continue;}Bitmap b=BitmapFactory.decodeByteArray(done,0,done.length);if(b!=null&&System.currentTimeMillis()-lastH264Ms>=120){homeFrames++;listener.homeFrame(b);}}catch(InterruptedException e){break;}catch(Throwable e){Log.e(TAG,"JPEG decode",e);}}Log.i(TAG,"JPEG worker exit");}
 private void rtpVideo(byte[]p){if(p.length<13||(p[0]&0xC0)!=0x80||(p[1]&0x7f)!=96)return;int rs=((p[2]&255)<<8)|(p[3]&255);if(lastVideoSeq>=0){int expected=(lastVideoSeq+1)&0xffff;if(rs!=expected){int gap=(rs-expected)&0xffff;if(gap>0&&gap<0x8000){rtpLoss+=gap;waitingIdr=true;au.reset();frag=null;currentTs=-1;Log.w(TAG,"H264 RTP gap expected="+expected+" got="+rs+" loss+="+gap+" -> wait IDR");}}}lastVideoSeq=rs;int ts=be32(p,4),len=p.length-12,type=p[12]&31;boolean marker=(p[1]&0x80)!=0;if(currentTs!=-1&&currentTs!=ts){au.reset();frag=null;auIdr=false;}currentTs=ts;if(type==28){if(len<2)return;boolean st=(p[13]&0x80)!=0,en=(p[13]&0x40)!=0;int ft=p[13]&31;if(st){frag=new ByteArrayOutputStream();startCode(frag);frag.write((p[12]&0xe0)|ft);frag.write(p,14,len-2);if(ft==5)auIdr=true;}else if(frag!=null&&len>2)frag.write(p,14,len-2);if(en&&frag!=null){try{frag.writeTo(au);}catch(Exception ignored){}frag=null;}}else{startCode(au);au.write(p,12,len);if(type==5)auIdr=true;}if(marker){byte[]data=au.toByteArray();au.reset();currentTs=-1;if(waitingIdr&&!auIdr){auIdr=false;return;}if(auIdr){waitingIdr=false;Log.i(TAG,"H264 IDR acquired bytes="+data.length);}auIdr=false;lastH264Ms=System.currentTimeMillis();h264Frames++;listener.h264Active();try{decoder.queue(data);}catch(Throwable e){waitingIdr=true;Log.e(TAG,"H264 queue",e);}}}
 private void audioLoop(){byte[]b=new byte[8192];while(running){try{DatagramPacket d=new DatagramPacket(b,b.length);try{audio.receive(d);}catch(SocketTimeoutException timeout){continue;}if(!d.getAddress().equals(host))continue;int l=d.getLength();audioRawPkts++;if(audioRawPkts==1)Log.i(TAG,"AUDIO first RX src="+d.getAddress().getHostAddress()+":"+d.getPort()+" len="+l+" pt="+(l>=2?(b[1]&0x7f):-1));if(l>=12&&(b[0]&0xC0)==0x80&&(b[1]&0x7f)==97){int n=(l-12)&~3;audioPkts++;audioBytes+=n;int w=audioTrack.write(b,12,n,AudioTrack.WRITE_BLOCKING);if(w<0)Log.w(TAG,"AUDIO write="+w);}}catch(Throwable e){if(running)Log.e(TAG,"AUDIO loop",e);}}Log.i(TAG,"AUDIO loop exit");}
 private void sendPad(){if(!running)return;try{ByteBuffer b=ByteBuffer.allocate(72).order(ByteOrder.LITTLE_ENDIAN);b.put((byte)'M').put((byte)'T').put((byte)'R').put((byte)'P').put((byte)2).put((byte)1).putShort((short)72).putInt(seq.incrementAndGet()).putLong(System.nanoTime()/1000).putInt(pad.buttons).putShort(pad.lx).putShort(pad.ly).putShort(pad.rx).putShort(pad.ry).putShort((short)pad.lt).putShort((short)pad.rt).put((byte)0);input.send(new DatagramPacket(b.array(),72,host,8767));padPkts++;}catch(Throwable e){if(running)Log.e(TAG,"PAD send",e);}}
 private void stats(){long n=System.currentTimeMillis();if(n-lastStatsMs>=2000){Log.i(TAG,"STATS video="+videoPkts+" mtj="+mtjPkts+" mtjLike="+mtjLikePkts+" pt96="+pt96Pkts+" other="+otherVideoPkts+" h264Frames="+h264Frames+" homeFrames="+homeFrames+" rtpLoss="+rtpLoss+" audioRaw="+audioRawPkts+" audioPT97="+audioPkts+" audioBytes="+audioBytes+" pad="+padPkts+" waitIDR="+waitingIdr);lastStatsMs=n;}}
 private void send(DatagramSocket s,String x,int port)throws Exception{byte[]b=x.getBytes(StandardCharsets.UTF_8);s.send(new DatagramPacket(b,b.length,host,port));}
 private void sendAsync(DatagramSocket s,String x,int port){Thread t=new Thread(()->{try{send(s,x,port);Log.i(TAG,"TX "+x+" ->"+port);}catch(Throwable e){if(running)Log.e(TAG,"TX "+x+" failed",e);}},"MT-start-tx");t.setDaemon(true);t.start();}
 private static void startCode(ByteArrayOutputStream o){o.write(0);o.write(0);o.write(0);o.write(1);}private static int be32(byte[]p,int o){return ByteBuffer.wrap(p,o,4).order(ByteOrder.BIG_ENDIAN).getInt();}
 public void close(){if(!closed.compareAndSet(false,true))return;Log.i(TAG,"CLOSE begin");running=false;try{if(video!=null&&!video.isClosed())sendAsync(video,"MTV2|STOP",8768);}catch(Throwable e){Log.w(TAG,"STOP queue failed",e);}if(inputExec!=null)inputExec.shutdownNow();if(video!=null)video.close();if(audio!=null)audio.close();if(input!=null)input.close();if(jpegWorker!=null)jpegWorker.interrupt();if(decoder!=null){try{decoder.close();}catch(Throwable e){Log.w(TAG,"decoder close",e);}}if(audioTrack!=null){try{audioTrack.stop();}catch(Throwable ignored){}try{audioTrack.release();}catch(Throwable ignored){}}Log.i(TAG,"CLOSE end");}
 private static String hexHead(byte[]b,int n){StringBuilder x=new StringBuilder();int m=Math.min(n,b.length);for(int i=0;i<m;i++){if(i>0)x.append(' ');x.append(String.format(java.util.Locale.US,"%02X",b[i]&255));}return x.toString();}

 public void sendTouch(int action, int[] ids, float[] xs, float[] ys, int count){
  if(closed.get() || !running)return;
  final int n=Math.max(0,Math.min(10,count));
  ByteBuffer bb=ByteBuffer.allocate(8+n*12).order(ByteOrder.LITTLE_ENDIAN);
  bb.put((byte)'M').put((byte)'T').put((byte)'T').put((byte)'1');
  bb.put((byte)1).put((byte)action).put((byte)n).put((byte)0);
  for(int i=0;i<n;i++){
   int x=Math.max(0,Math.min(1279,Math.round(xs[i]*1279f)));
   int y=Math.max(0,Math.min(719,Math.round(ys[i]*719f)));
   bb.putInt(ids[i]).putShort((short)x).putShort((short)y).putShort((short)12).putShort((short)12);
  }
  latestTouchPacket.set(Arrays.copyOf(bb.array(),bb.position()));
  if(n==0) touchReleaseRepeats.set(3); else touchReleaseRepeats.set(0);
 }
 private void sendTouchLatest(){
  if(!running||input==null||input.isClosed())return;
  byte[] p=latestTouchPacket.get(); if(p==null)return;
  int contacts=p.length>=7?(p[6]&255):0;
  try{
   input.send(new DatagramPacket(p,p.length,host,8767)); touchTxPkts++;
   if(touchTxPkts==1||(touchTxPkts%300)==0)Log.i(TAG,"TOUCH TX packet="+touchTxPkts+" contacts="+contacts);
   if(contacts==0){int left=touchReleaseRepeats.decrementAndGet();if(left<=0){touchReleaseRepeats.set(0);latestTouchPacket.compareAndSet(p,null);}}
  }catch(Throwable e){if(running)Log.w(TAG,"TOUCH TX "+e.getClass().getSimpleName()+": "+e.getMessage());}
 }
}
